//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id { get; set; }
        public string path { get; set; }
        public string ext { get; set; }
        public string peiceofEquipment { get; set; }
        public string height { get; set; }
        public string width { get; set; }
        public string alt { get; set; }
    }
}
