//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Formula { get; set; }
        public string Location { get; set; }
        public string Units { get; set; }
        public string TriggerLevel { get; set; }
        public string CurrentStock { get; set; }
        public string Supplier { get; set; }
        public string SupplierProductCode { get; set; }
        public string CASCode { get; set; }
        public string BatchCode { get; set; }
        public string Purity_Grade { get; set; }
        public string Expiry_Date { get; set; }
        public string SummaryOfHazards { get; set; }
        public string OrderedBy { get; set; }
        public string Reviewed { get; set; }
        public string Purpose { get; set; }
        public string LinkToMSDS { get; set; }
        public string COSHHCompleted { get; set; }
        public string MSDSAvailable { get; set; }
        public string Catagory { get; set; }
    }
}
