//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab_Stores
    {
        public int ID { get; set; }
        public string Location { get; set; }
        public string Custodian { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public string UserGuide { get; set; }
        public string RiskAssessment { get; set; }
        public string MaterialSpecific { get; set; }
        public string ManuelHandling { get; set; }
        public string ApprovedSuppliers { get; set; }
        public string OrderRequestProcedure { get; set; }
        public string Category { get; set; }
    }
}
