//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sheet1_
    {
        public string Name_of_Substance { get; set; }
        public string Formula { get; set; }
        public string Location { get; set; }
        public string Units { get; set; }
        public string Trigger_Level { get; set; }
        public string Current_Stock_Level { get; set; }
        public string Supplier { get; set; }
        public string Supplier_Product_Code { get; set; }
        public string CAS_Code { get; set; }
        public string Batch_Code { get; set; }
        public string Purity_Grade { get; set; }
        public string Expiry_Date { get; set; }
        public string Summary_of_Hazards { get; set; }
        public string Ordered_by { get; set; }
        public string Reviewed { get; set; }
        public string Purpose__Teaching_Research_etc_ { get; set; }
        public string Link_to_MSDS { get; set; }
        public string Category { get; set; }
        public string COSHH_completed__Y_N_ { get; set; }
        public string MSDS_Available__Y_N_ { get; set; }
        public string F21 { get; set; }
        public string F22 { get; set; }
        public string F23 { get; set; }
        public int ID { get; set; }
    }
}
