//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labManagmentSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Research_Equip
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Specifications { get; set; }
        public string QuickUserGuide { get; set; }
        public string FullUserManual { get; set; }
        public string CurrentRiskAssessment { get; set; }
        public string LocalRules { get; set; }
        public string HardwareFixes { get; set; }
        public string SoftwareFixes { get; set; }
        public string Maintenance { get; set; }
        public string QuartzyLink { get; set; }
        public Nullable<bool> ResearchEquipment { get; set; }
        public string Custodian { get; set; }
    }
}
